apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-restful
  namespace: twdps-core-labs-team-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-restful
  template:
    metadata:
      labels:
        app: hello-restful
    spec:
      containers:
      - image: ghcr.io/thoughtworks-dps/hello-restful:dev.b5df64f
        imagePullPolicy: Always
        name: hello-restful
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr
