---
version: 2.1

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

executors:
  infra-image:
    docker:
      - image: twdps/circleci-kube-ops:alpine-0.7.0
    
commands:
 set-environment:
    parameters:
     cluster:
       description: cluster to be deployed to
       type: string
    steps:
      - run:
          name: pull kubeconfig
          command: |
            mkdir -p ~/.kube
            ENV=<< parameters.cluster >> op inject -i tpl/kubeconfig.tpl -o ~/.kube/config

jobs:
  deploy-namespaces:
    executor: infra-image
    shell: op run --env-file=op.prod.env -- /bin/bash -eo pipefail
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: prod-us-east-1
      - run:
          name: deploy production namespaces
          command: bash scripts/deploy-namespaces.sh
      - run:
          name: deploy httpbin validate app
          command: kubectl apply -f httpbin-deployment.yaml
      - run:
          name: validate production namespace
          command: |
            sleep 5
            bats test/validate_istio_injection.bats --verbose-run
      - run:
          name: delete httpbin validate app
          command: kubectl delete -f httpbin-deployment.yaml
          when: always

workflows:
  version: 2
  lab-platform-simple-namespaces-pipeline:
    jobs:
      - deploy-namespaces:
          context: twdps-core-labs-team
          filters: *on-push-main
